In [2]:
import numpy as np
from scipy.stats import kstest, shapiro, anderson, norm, chi2
import pandas as pd

In [3]:
df = pd.read_csv('FreeLancerT.csv')
print(df)

                  Country CountryCode Continent         C    C_Test      Html  \
0                   Aruba         ABW       NaN  1.918226       NaN  4.795565   
1                  Angola         AGO        AF  0.023228  0.003871  0.011614   
2                 Albania         ALB        EU  7.783173  0.241072       NaN   
3                 Andorra         AND        EU  7.229090  0.000000  7.229090   
4    United Arab Emirates         ARE        AS  7.176023  0.291357  7.996140   
..                    ...         ...       ...       ...       ...       ...   
185               Vanuatu         VUT        OC  0.739454  0.000000  0.369727   
186                 Samoa         WSM        OC  4.112624  0.000000  2.570390   
187           Yemen  Rep.         YEM        AS  0.080065  0.000000  0.076426   
188          South Africa         ZAF        AF  1.109516  0.027283  1.227744   
189                Zambia         ZMB        AF  0.113654  0.000000  0.131600   

     Html_test       Java  

In [4]:
df_numerical_columns = df.select_dtypes(include='number')
print(df_numerical_columns)

            C    C_Test      Html  Html_test       Java  Java_test        PHP  \
0    1.918226       NaN  4.795565   0.959113   2.877339   0.000000   3.836452   
1    0.023228  0.003871  0.011614   0.000000   0.023228   0.000000   0.019357   
2    7.783173  0.241072       NaN   0.551021   6.956642   0.241072  12.397975   
3    7.229090  0.000000  7.229090   1.445818  10.120726   0.000000   8.674908   
4    7.176023  0.291357  7.996140   0.291357   4.478270   0.140283   7.629246   
..        ...       ...       ...        ...        ...        ...        ...   
185  0.739454  0.000000  0.369727   0.000000   0.369727   0.000000   0.739454   
186  4.112624  0.000000  2.570390   0.514078   4.626702   0.000000   3.598546   
187  0.080065  0.000000  0.076426   0.007279   0.043672   0.000000   0.058229   
188  1.109516  0.027283  1.227744   0.023645   0.836685   0.030921   1.113154   
189  0.113654  0.000000  0.131600   0.000000   0.095709   0.000000   0.131600   

     PHP_test  
0    0.0000

### 1_INLOCUIREA DATELOR LIPSA CU MEDIA
- inplace = true face ca df_numerical_columns sa fie updatat cu valorile
- inplace = false returneaza un alt dataframe

In [5]:
for column in df_numerical_columns.columns:
    column_mean = df_numerical_columns[column].mean()
    print (column_mean)
    #fill values of 0 and NaN with mean 
    df_numerical_columns[column].replace(0, column_mean, inplace=True)
    df_numerical_columns[column].fillna(column_mean, inplace=True)

print(df_numerical_columns)

4.712177267326316
0.14021929806878308
4.593976102714286
0.45661185754736844
3.5588564581578943
0.1789726627263158
4.928756746689474
0.5135805405
            C    C_Test      Html  Html_test       Java  Java_test        PHP  \
0    1.918226  0.140219  4.795565   0.959113   2.877339   0.178973   3.836452   
1    0.023228  0.003871  0.011614   0.456612   0.023228   0.178973   0.019357   
2    7.783173  0.241072  4.593976   0.551021   6.956642   0.241072  12.397975   
3    7.229090  0.140219  7.229090   1.445818  10.120726   0.178973   8.674908   
4    7.176023  0.291357  7.996140   0.291357   4.478270   0.140283   7.629246   
..        ...       ...       ...        ...        ...        ...        ...   
185  0.739454  0.140219  0.369727   0.456612   0.369727   0.178973   0.739454   
186  4.112624  0.140219  2.570390   0.514078   4.626702   0.178973   3.598546   
187  0.080065  0.140219  0.076426   0.007279   0.043672   0.178973   0.058229   
188  1.109516  0.027283  1.227744   0.023645 

/run/user/1000/ipykernel_44150/3393352106.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_numerical_columns[column].replace(0, column_mean, inplace=True)
/run/user/1000/ipykernel_44150/3393352106.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df

### (varianta2) 1_INLOCUIREA DATELOR LIPSA CU MEDIA - versiunea cu masti -
- aici e acelasi aproach ca mai sus doar ca folosesc masks pentru a obtine acelasi rezultat

In [6]:
for column in df_numerical_columns.columns:
    column_mean = df_numerical_columns[column].mean()
    print(column_mean)
    mask_is_zero = df_numerical_columns[column] == 0
    mask_is_nan = pd.isna(df_numerical_columns[column])
    #sau
    mask_is_nan = df_numerical_columns[column].isna()
    df_numerical_columns[mask_is_zero] = column_mean
    df_numerical_columns[mask_is_nan] = column_mean

print(df_numerical_columns)

4.984987530171525
0.20073499513004733
4.811585497053383
0.6272404990519113
3.7274338693337947
0.24961976643407208
5.084401696584932
0.6919822019368421
            C    C_Test      Html  Html_test       Java  Java_test        PHP  \
0    1.918226  0.140219  4.795565   0.959113   2.877339   0.178973   3.836452   
1    0.023228  0.003871  0.011614   0.456612   0.023228   0.178973   0.019357   
2    7.783173  0.241072  4.593976   0.551021   6.956642   0.241072  12.397975   
3    7.229090  0.140219  7.229090   1.445818  10.120726   0.178973   8.674908   
4    7.176023  0.291357  7.996140   0.291357   4.478270   0.140283   7.629246   
..        ...       ...       ...        ...        ...        ...        ...   
185  0.739454  0.140219  0.369727   0.456612   0.369727   0.178973   0.739454   
186  4.112624  0.140219  2.570390   0.514078   4.626702   0.178973   3.598546   
187  0.080065  0.140219  0.076426   0.007279   0.043672   0.178973   0.058229   
188  1.109516  0.027283  1.227744   0.0

### 2_STANDARDIZAREA DATELOR
- datele sunt standard daca au media 0 si abaterea standard 1
- pentru a standardiza un set de date pt fiecare intrare de pe coloana facem x = (x-medie)/std

In [7]:
for column in df_numerical_columns.columns:
    df_numerical_columns[column] = (df_numerical_columns[column] - df_numerical_columns[column].mean())/df_numerical_columns[column].std() 

#print(df_numerical_columns) 
for column in df_numerical_columns.columns:
    print(f"{df_numerical_columns[column].mean():.2f} ~ {df_numerical_columns[column].std():.2f}");

-0.00 ~ 1.00
0.00 ~ 1.00
-0.00 ~ 1.00
0.00 ~ 1.00
0.00 ~ 1.00
-0.00 ~ 1.00
-0.00 ~ 1.00
0.00 ~ 1.00


### 3_MATRICE DE COVARIANTA/CORELATIE
- Matricele de mai jos sunt facute pe tot setul de date fara a fi grupa dupa un criteriu cum ar fi tara

In [8]:
matrice_cov = np.cov(df_numerical_columns, rowvar=False)
matrice_corelatii = np.corrcoef(df_numerical_columns, rowvar=False)
print(matrice_cov)
print('==========')
print(matrice_corelatii)

[[1.         0.23545745 0.5942541  0.95190628 0.92712237 0.23100884
  0.61105094 0.95294955]
 [0.23545745 1.         0.72918106 0.17238558 0.3733687  0.64796668
  0.68563021 0.230902  ]
 [0.5942541  0.72918106 1.         0.47594744 0.74347455 0.62494949
  0.95604218 0.5209502 ]
 [0.95190628 0.17238558 0.47594744 1.         0.82747001 0.16516352
  0.46316623 0.98478931]
 [0.92712237 0.3733687  0.74347455 0.82747001 1.         0.4125442
  0.76771716 0.83520522]
 [0.23100884 0.64796668 0.62494949 0.16516352 0.4125442  1.
  0.59406137 0.16625731]
 [0.61105094 0.68563021 0.95604218 0.46316623 0.76771716 0.59406137
  1.         0.53116698]
 [0.95294955 0.230902   0.5209502  0.98478931 0.83520522 0.16625731
  0.53116698 1.        ]]
[[1.         0.23545745 0.5942541  0.95190628 0.92712237 0.23100884
  0.61105094 0.95294955]
 [0.23545745 1.         0.72918106 0.17238558 0.3733687  0.64796668
  0.68563021 0.230902  ]
 [0.5942541  0.72918106 1.         0.47594744 0.74347455 0.62494949
  0.956042

### 4_MATRICE DE COVARIANTA/CORELATIE RAPORTATA LA O VALOARE
- se foloseste de exemplu daca doresc sa vad corelatia dintre variabilele numerice dupa un camp
- EX: Corelatia si covarianta intre numarul de developeri de diferite limbaje si tara din care provin
- Rezultatul este un vector de matrici. 
    - Fiecare element din vector reprezinta o matrice de MxM variabile studiate
    - Rezultatul final va fi o structura de tip QxMxM unde Q = nr tari studiate | M = nr variabile studiate 

In [9]:
#selecteaza toate liniile de pe coloana 0
country_list = df.iloc[:, 1].unique()
#print(country_list)
number_of_unique_countires = len(df.iloc[:, 1].unique())
number_of_numerical_values = df_numerical_columns.shape[1]

corelated_cov_matrix = np.empty(shape=(number_of_unique_countires, number_of_numerical_values, number_of_numerical_values))
corelated_std_matrix = np.empty(shape=(number_of_unique_countires, number_of_numerical_values, number_of_numerical_values))

index = 0
for country in country_list:
    country_rows_mask = df['CountryCode'] == country
    df_current_county_data = df[country_rows_mask]
    df_current_numerical = df_current_county_data.select_dtypes(include='number')
    corelated_cov_matrix[index] = np.cov(df_current_numerical)
    corelated_std_matrix[index] = np.std(df_current_numerical, axis=0)
    
print(corelated_cov_matrix)
print(corelated_std_matrix)

[[[4.01782088e-003 4.01782088e-003 4.01782088e-003 ... 4.01782088e-003
   4.01782088e-003 4.01782088e-003]
  [4.01782088e-003 4.01782088e-003 4.01782088e-003 ... 4.01782088e-003
   4.01782088e-003 4.01782088e-003]
  [4.01782088e-003 4.01782088e-003 4.01782088e-003 ... 4.01782088e-003
   4.01782088e-003 4.01782088e-003]
  ...
  [4.01782088e-003 4.01782088e-003 4.01782088e-003 ... 4.01782088e-003
   4.01782088e-003 4.01782088e-003]
  [4.01782088e-003 4.01782088e-003 4.01782088e-003 ... 4.01782088e-003
   4.01782088e-003 4.01782088e-003]
  [4.01782088e-003 4.01782088e-003 4.01782088e-003 ... 4.01782088e-003
   4.01782088e-003 4.01782088e-003]]

 [[3.08137750e-316 3.08137810e-316 3.08137869e-316 ... 3.08137953e-316
   3.08138012e-316 3.08138071e-316]
  [3.08138131e-316 3.08138190e-316 3.08138249e-316 ... 3.08138422e-316
   3.08138462e-316 3.08138482e-316]
  [3.08138496e-316 3.08138556e-316 3.08138615e-316 ... 3.08138783e-316
   3.08138842e-316 3.08138892e-316]
  ...
  [3.08139633e-316 3.08

### 5_TESTE DE CONCORDANTA PENTRU VERIFICAREA DISTRIBUTIEI NORMALE
- se folosesc functii din scipy 
    - kstest (Komogorov-Smirnov)
    - Shapiro 
    - Anderson
    - chi2 
- se aplica pe setul de variabile numerice (nu necesita matrici de concordanta)
- functia va stoca intr-o matrice rezultatele unde vom avea x = nr de teste facute coloane si y = nr de variabile numerice linii
    - ex: matricea va avea pe coloane cate o variabila numerica si pe linie valorile date de fiecare functie de testare
- !functia nu implementeaza testul chi2 --> se poate scrie de mana sau se poate folosi o librarie 
 

In [16]:
statistical_tests_number = 3
number_of_numerical_values = len(df_numerical_columns.columns)
corelation_tests_matrix = np.empty(shape=(number_of_numerical_values, statistical_tests_number))

column_index = 0
# toate testele facute dau output la mai mult parametrii din care pe noi ne interesaza pvalue
# asa ca toate expresiile test_ktest[someIndex] extrag pvalue sau un indicator echivalent din outputs
for column in df_numerical_columns.columns:
    # ktest --> Komogorov-Smirnov
    test_kstest = kstest(df_numerical_columns[column], "norm")
    corelation_tests_matrix[column_index][0] = test_kstest[1] > 0.01
    # shapiro 
    test_shapiro = shapiro(df_numerical_columns[column])
    corelation_tests_matrix[column_index][1] = test_shapiro[1] > 0.01
    # anderson
    test_anderson = anderson(df_numerical_columns[column])
    # print(test_anderson)
    # testul anderson are 2 parti: test_anderson[0] --> valoare statistica si test_anderson[1] --> valori critice
    # pentru ca testul anderson sa fie valid valoare statistica trebuie sa fie mai mica decat toate valorice critice
    corelation_tests_matrix[column_index][2] = any(test_anderson[0] < test_anderson[1])
    
print(corelation_tests_matrix)

[[0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [7.74860419e-304 7.74860419e-304 7.74860419e-304]
 [7.74860419e-304 7.74860419e-304 7.74860419e-304]
 [7.74860419e-304 7.74860419e-304 7.74860419e-304]
 [7.74860419e-304 7.74860419e-304 7.74860419e-304]
 [7.74860419e-304 7.74860419e-304 7.74860419e-304]
 [7.74860419e-304 7.74860419e-304 7.74860419e-304]
 [7.74860419e-304 7.74860419e-304 5.45361240e-312]]
